<?nextrec?>
<?definegroup 1 "=$Model$="?>
<?ifendgroup 1 ?>
}

<?include "../extensions/=$LastModel&cuul$=Model.swift" ?>
<?endif?>
<?ifnewgroup 1 ?>
<?set lastmodel = =$Model$= ?>
<?output "../code/Modules/=$module$=/Models/=$Model&cuul$=Model.swift"?>
//
//  =$Model&cuul$=Model.swift
//
//  Generated by Notenik on =$today$=
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Vapor
import Fluent

final class =$Model&cuul$=Model: Model {
    
    static let schema: String = "=$Model&c_lll$=s"
    
<?include "../includes/field-keys/=$model$=.swift" ?>

<?include "../includes/wrappers/=$model$=.swift" ?>

	init() { }
    
<?include "../includes/init-parms/=$model$=.swift" ?>
<?include "../includes/self-assignments/=$model$=.swift" ?>
<?endif?>
<?loop?>
