<?nextrec?>
<?definegroup 1 "=$Module$="?>
<?ifendgroup 1 ?>
}
<?endif?>
<?ifnewgroup 1 ?>
<?output "../code/Modules/=$module$=/Migrations/=$module$=Migration.swift"?>
//
//  =$module$=Migration.swift
//
//  Generated by Notenik on =$today$=
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Vapor
import Fluent

struct =$module$=Migration: Migration {

<?include "../includes/migration/=$module$=-prepare.swift" ?>

<?include "../includes/migration/=$module$=-revert.swift" ?>

<?endif?>
<?loop?>
