<?output "../code/NotenikMigration.swift"?>
//
//  NotenikMigration.swift
//
//  Generated by Notenik on =$today$=
//
//  Copyright © 2020 Herb Bowie (https://powersurgepub.com)
//
//  This programming code is published as open source software under the
//  terms of the MIT License (https://opensource.org/licenses/MIT).
//

import Foundation
import Fluent

struct NotenikMigration: Migration {

<?include "../includes/migration/prepare.swift" ?>

<?include "../includes/migration/revert.swift" ?>

<?nextrec?>
<?definegroup 1 "=$Model$="?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?endif?>
<?loop?>
}